history_length: 5
mail:
  body: "Zisternen-F체llstand hat Schwellwert erreicht: {Ist} <= {Schwellwert} (Ist\
    \ <= Schwellwert)\n\nF체llst채nde sind:\n\t0: < 200 L\n\t1: 200 - 1200 L\n\t2: 1200\
    \ - 2500 L\n\t3: 2500 - 5000 L\n\t4: 5000 L"
  filllevel_threshold: 3
  recipients:
  - levin.fober@gmail.com
  reminder_interval: 86400
  server_address: smtp.gmail.com
  server_password: ffdbibvqgxxfbqbe
  server_port: 465
  server_user: printermailerlevin@gmail.com
  subject: Alarm Zisternen-F체llstand ({Ist})
max_cache_age: 5
